### ISSUE TITLE
'FortranFile' object has no attribute 'file'

### ISSUE THREAD

**Issue by mcduffie** [ReFRACtor/GENOD#2]
I believe the version of common recorded in the repo probably needs updating. I get the following error when running run_RT_Ref_OD.py
```
Traceback (most recent call last):
  File "./run_RT_Ref_OD.py", line 175, in <module>
    gncObj.arrOD(iProfs=args.profiles)
  File "/scratch-science2/algorithm/mcduffie/refractor/genod/GENOD_compute.py", line 578, in arrOD
    wn, od = lblTools.readOD(odPath, double=True)
  File "./common/lblTools.py", line 123, in readOD
    ff, od = readTape12(path, double=double)
  File "./common/lblTools.py", line 391, in readTape12
    fortranFile = FortranFile.FortranFile(fileName)
  File "./common/FortranFile.py", line 14, in __init__
    self.file=open(fileName,'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'LBL_OD_dir/2016-04-14T01:13:30.00010000Z/ODint_063_25000-26999_all_molecules'
Exception ignored in: <bound method FortranFile.__del__ of <FortranFile.FortranFile object at 0x7f2389619048>>
Traceback (most recent call last):
  File "./common/FortranFile.py", line 107, in __del__
    self.close()
  File "./common/FortranFile.py", line 102, in close
    if self.file:
AttributeError: 'FortranFile' object has no attribute 'file'
```

**Comment by pernak18** [comment]
this is an artifact of b8a2aae2171dd6b13e7f5e46d7f54e93d7d561cf. i did some testing with the new commit and was able to reproduce the error, which i have seen before, but not in the original code we delivered. in other words, my commit broke things. the LBL runs were crashing and thus not producing a `file` to be assigned to `self.file` in `FortranFile.py`

commit fc2a501f9f530cd463e2ab27340aa687c4134daa fixed the bugs i introduced, and my test produced a new netCDF for the 27 molecules, and profile 0.

@mcduffie if you can run again and verify that you can get past this error, i'll close the issue. thanks

**Comment by mcduffie** [comment]
I am still getting this error, even after removing the original clone and recreating the checkout and Python environment. My LBL_OD_dir directories are all empty:

```
> ls LBL_OD_dir/*
LBL_OD_dir/2016-04-14T00:56:26.00000000Z:

LBL_OD_dir/2016-04-14T01:06:02.00003000Z:

LBL_OD_dir/2016-04-14T01:13:30.00010000Z:

LBL_OD_dir/2016-04-14T01:25:14.00000000Z:
```

**Comment by mcduffie** [comment]
I see this error in the output, possibly related:

```
 ERROR: BOUNDARY PRESSURES FOR LBLRTM LAYERS ARE POSITIVE OR NOT IN DESCENDING ORDER

      PBND
   10.0000   21.5440   38.3120   68.1290  100.0000  133.3520  161.5600  215.4430  261.0160  316.2270
  464.1600  510.8980  681.2910  825.4020  908.5140 1000.0000 1100.7000 1211.5300 1333.5200 1467.8000
 1615.6000 1778.2800 1957.3400 2154.4300 2371.3600 2610.1700 2872.9900 3162.2900 3480.7100 3831.1900
 4216.9600 4641.5800 5108.9600 5623.3900 6189.6300 6812.9500 7498.9600 8254.0600 9085.180010000.0000
11006.900012115.200013335.200014677.900016156.100017782.900019573.500021544.400023713.700026101.6000
28729.800031622.700034806.900038311.700042169.800046416.000051089.800056234.200061896.600068129.1000
74989.300082540.200090851.4000********************
STOP  PBND
```

**Comment by pernak18** [comment]
yes, it looks like you're getting the same error for a different reason this time. before, i had the wrong pressure boundaries (surface and TOA) and an indexing bug. now, the pressure profile looks different. my code assumes a surface-to-TOA pressure profile, and the pressures must be in mbar. the profile you provided looks like Pa. could you try reversing the profile and converting to mbar?

i can pretty easily automate the reversal, but i wanna make sure this solves your error

**Comment by pernak18** [comment]
@mcduffie commit 2603d39687312b1c8b7a8dada3908ffaea1f8def should take care of the problem. i was able to generate full netCDF files for all of the "experiments" (molecule subsets) and profiles given the new inputs. hopefully it runs end-to-end for you now

**Comment by mcduffie** [comment]
Thanks, this appears to have fixed the problem.
